### ISSUE TITLE
[조회화면(관리자 모드, 조회 모드)] 출력 칸에 입력가능 

### ISSUE THREAD

**Issue by 1317Stephen** [shyun-ab/Software_Verification#1]
현재 잔액보여주는 두 화면에서 입력 불가해야 하는데 입력할 수 있다
![default](https://user-images.githubusercontent.com/33503422/40605764-5ad86a86-629e-11e8-91bc-4969ca565cd0.png)

<해결방법>
Java GUI에서 textField가 아니라 JLabel 등을 사용한다

**Comment by seokk1209** [comment]
출력칸에는 입력할수 없도록 모든 칸을 변경하였습니다.
