### ISSUE TITLE
[공통(모든 모드)] 입력 값 예외 처리

### ISSUE THREAD

**Issue by 1317Stephen** [shyun-ab/Software_Verification#2]
<해당 테스트 케이스>
atm-6:Test   Case 2
atm-7:Test Case 3
atm-8:Test Case 4
atm-9:Test Case 5
atm-10:Test Case 6
atm-13:Test   Case 9
atm-14:Test Case 10
atm-21:Test   Case 17
atm-22:Test Case 18
atm-23:Test Case 19
atm-24:Test Case 20
atm-25:Test Case 21
atm-26:Test Case 22
atm-27:Test Case 23
atm-28:Test Case 24
atm-29:Test Case 25
atm-30:Test Case 26
atm-31:Test Case 27
atm-32:Test Case 28
atm-33:Test Case 29
atm-34:Test Case 30
atm-39:Test Case 31
atm-42:Test   Case 2
atm-43:Test Case 3
atm-44:Test Case 4
atm-45:Test Case 5
atm-46:Test Case 6
atm-50:Test   Case 10
atm-51:Test Case 11
atm-52:Test Case 12
atm-53:Test Case 13
atm-54:Test Case 14
atm-55:Test Case 15
atm-56:Test Case 16
atm-57:Test Case 17
atm-58:Test Case 19
atm-59:Test Case 20
atm-60:Test Case 21
atm-61:Test Case 22
atm-62:Test Case 23
atm-63:Test Case 24
atm-64:Test Case 25
atm-65:Test Case 26
atm-66:Test Case 27
atm-67:Test Case 28
atm-68:Test Case 29
atm-69:Test Case 30

<문제>
1. 숫자가 아닌 값 입력 
2. 아주 큰 수 입력
3. (ID, PW 입력 시에) 소숫점 입력
4. 마이너스 입력

<해결>
1. 아예 입력 불가능하고 모두 버튼으로 대체(실제 ATM처럼 입력 없이 버튼만 누르게)
2. 특정 변수들의 입력 시에 모두 에러 메세지 출력(위의 경우....)

**Comment by seokk1209** [comment]
예외처리 적용하였습니다.
