### ISSUE TITLE
[관리자 모드: 출금] 잔고보다 큰 수 입력시에 에러 메세지가 없을 경우

### ISSUE THREAD

**Issue by 1317Stephen** [shyun-ab/Software_Verification#4]
<해당 테스트 케이스>
atm-48:Test   Case 8

<해결>
1.큰수 입력->에러 메세지
2.아예 입력 불가하게 입력 텍스트 필드에 제한 두기

**Comment by seokk1209** [comment]
잔고보다 큰 수 입력에 대한 에러처리를 하였습니다.

ATM 최대잔고는 화폐별 500매 입니다.
