### ISSUE TITLE
[Jackpot] 잭팟이 터지는 횟수 이상 있음& 터지는 경우를 명확히 해야 함 & 잭팟 터져도 잔고 변화 없음

### ISSUE THREAD

**Issue by 1317Stephen** [shyun-ab/Software_Verification#5]
<문제>
1. 언제 잭팟이 터지나? (아이디&&패스워드 바르게 입력했을 때, 아이디만 바르게 입력했을 때.....)
2. 연속으로 잭팟이 터질 때 있음(테스트 해 봤을 때 5번째&6번째 시도 했을 때 모두 터짐)
3. 잔고 0 일 때 잭팟 터져도 잔고 그대로

<해결>
1. 기능의 적확한 명세 & 이에 따른 코드 보정
2. 잭팟이 터지는 난수 설정을 조금 더 섬세하게(연속으로 난수가 생성 되는 경우 예외처리 해서 불가하도록) 설정
3. 예외처리

**Comment by seokk1209** [comment]
잭팟이 터지는 경우는 하루의 1번 출금시에만으로 가능하도록 타이머와 초기화에어 있어서 발생하는 오류를 수정하엿습니다.
