### ISSUE TITLE
[공통] (명세에 명시된)반응이 1초 내로 이뤄지지 않음

### ISSUE THREAD

**Issue by 1317Stephen** [shyun-ab/Software_Verification#6]
<문제>
1. 반응이 없거나
2. (여러번 반복하거나 큰 수 입력 등의 경우) 1초 이내로 이뤄지지 않음

**Comment by seokk1209** [comment]
예외처리후 멈춤이나 시간이 지연되는 현상은 각 메뉴에 대해서 없는것을 확인하였습니다.
그러나 이 기능은 시스템 자체의 기능이 아닌만큼 실행환경에 따라 달라질수 있습니다.
지속해서 이런 문제가 발생할경우 구체적인 케이스를 명시하여 주시면 픽스하도록 하겠습니다: )
