### ISSUE TITLE
[입금] 잔고가 일정 범위 이상 넘어가면 엉뚱한 에러 메세지가 뜨며 입금 불가

### ISSUE THREAD

**Issue by 1317Stephen** [shyun-ab/Software_Verification#7]
<문제>
1. 잔고가 일정 범위보다 커지면 "비밀번호 확인하세요" 에러 메세지

<해결>
1. 코드 확인: 에러 메세지가 터지는 경우의 처리를 잘못한 것인지, 아니면 일정 범위 이상의 잔고 금액은 비밀번호 입력창으로 넘어가는(버퍼가 터진다든가.....) 것인지 등

**Comment by seokk1209** [comment]
개인의 일반계좌가 가질수 있는 금액은 10억
 ATM이 가질수 있는 최대 금액은 각 화폐별 500매로 한정하였습니다.

따라서 잔고가 일정범위 (integer ) 범위 밖으로 넘어가는 경우가 없도록 하고, 입력에 있어서도 integer 제외한 값에 대해  예외처리를 하였습니다.
