### ISSUE TITLE
[관리자 모드] ATM 잔고 50만원 이하여도 "잔고 부족" 메세지 출력 안 함.

### ISSUE THREAD

**Issue by 1317Stephen** [shyun-ab/Software_Verification#8]
<문제>
1. 에러 메세지 자체의 부재

<해결>
1. 해당 에러 메세지가 구현이 안 돼 있는 건지, 아니면 구현 돼 있음에도 해당 경우를 처리를 못 하는 것인지

**Comment by seokk1209** [comment]
잔고 부족에 대해서는 출금에 필요한 5만원권과 1만원권 각각 30매 이하가 될 시
메인메뉴 하단에 출력해주도록 수정
